:source-highlighter: highlight.js
:highlightjs-languages: crystal
:toc: 
:toclevels: 4 
:icons: font 
== History

Tablo is a port of [Matt Harvey's
Tabulo](https://github.com/matt-harvey/tabulo) Ruby gem to the Crystal
Language.

The first version of Tablo (v0.10.1) was released on November 30, 2021,
in the context of learning the Crystal language, which explains its
relative limitations compared to Tabulo v2.7, the current version
at that time, subject of the software port.

So this version of Tablo (v1.0) is a complete rewrite of the library.

Compared to the first version, it offers extended capabilities,
sometimes at the cost of a modified syntax. It also offers new features,
such as the ability to add a Summary table, powered by user-defined
functions (such as sum, mean, etc.), the ability to process any
Enumerable data, as well as elaborate layout possibilities: grouped
columns, different types of headers (title, subtitle, footer), linked or
detached border lines, etc.

While overall, Tablo remains, in terms of its functionalities, broadly
comparable, with a few exceptions, to the Tabulo v3.0 version of Matt
Harvey, the source code, meanwhile, has been deeply redesigned.

// {empty} +

== Features

- Presents a DRY API that is column-based, not row-based, meaning header and body rows are automatically in sync
- Lets you set fixed column widths, then either wrap or truncate the overflow
- Alternatively, “pack” the table so that columns are auto-sized to their contents
- Cell alignment is configurable, but has helpful content-based defaults (numbers right, strings left)
- Tabulate any Enumerable: the underlying collection need not be an array
- Step through your table a row at a time, printing as you go, without waiting for the underlying collection to load. In other words, have a streaming interface for free.
- Add optional title, subtitle and footer to your table
- The header row can be repeated at arbitrary intervals
- Newlines within cell content are correctly handled
- Multibyte Unicode characters are correctly handled (needs the "uniwidth" library)
- Option to preserve whole words when wrapping content
- Apply colors and other styling to table content and borders, without breaking the table
- Easily transpose the table, so that rows are swapped with columns
- Choose from several border configurations, including predefined ones such as Markdown, Ascii (default), and user-defined ones.
- Adjacent columns can be capped by a group header
- A summary table can be added to apply user-defined functions to numeric values of a column

// {empty} +


== Installation

1. Add the dependency to your shard.yml:
[literal]
 dependencies:
   tablo:
     gitlab: hutou/tablo
2. Run `shards install`
3. And insert the line

[source,crystal]
----
require "tablo"
----
at the beginnning of your app.

:toc: 
:toclevels: 4 

== Tutorial

In this tutorial, we'll start with a very simple example, which we'll build on as we go along to gradually discover all the possibilities offered by the Tablo library. 

Here's a first look at how to use Tablo to lay out a simple table of integers.

[source,crystal]
----
1	require "tablo"
2	
3	table = Tablo::Table.new([1, 2, 3]) do |t|
4	    t.add_column("itself", &.itself)
5	    t.add_column(2, header: "Double") {|n| n * 2}
6	    t.add_column(:column_3, header: "String") {|n| n.even?.to_s}
7	end
8	puts table
----

or

[source,crystal]
----
1	require "tablo"
2	
3	table = Tablo::Table.new([1, 2, 3])
4	table.add_column("itself", &.itself)
5	table.add_column(2, header: "Double") {|n| n * 2}
6	table.add_column(:column_3, header: "String") {|n| n.even?.to_s}
8	puts table
----

[literal]
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+

A great deal of information can already be extracted from this simple example. Let's list them:

- The only parameter required to create the table is the data source (the array of integers), but to produce a result, you obviously need to add columns

- Any number of columns can be defined, each requiring an identifier and a Proc to extract the data from each row of the source, and, if necessary, modify its type and value

- The column identifier can be of type String, Integer or Symbol. By default, the column header takes the value of the identifier, unless the optional `header:` parameter is used

- Columns are the same width

- We see two types of row: header and body. 

- Number columns are aligned to the right, and text columns to the left, for both headers and body.

- Default borders use the classic `Ascii` type 

Now, let's look at borders

=== Borders

Each border type is defined by a string of exactly 16 characters, which are
then converted into 16 strings of up to 1 character each.  The definition
string can contain any character, but two of them have a special meaning:
after conversion, the uppercase E is replaced by an empty string, and the
underscore character is replaced by a space. +
_Please note that using the capital E character may cause alignment
 difficulties._

The first 9 characters define the junction or intersection of horizontal and
vertical lines.

[cols="1,5"]
|===
|Index | Description 

| 0 | Top left corner
| 1 | Top middle junction
| 2 | Top right corner
| 3 | Middle left junction
| 4 | Middle middle intersection
| 5 | Middle right junction
| 6 | Bottom left corner
| 7 | Bottom middle junction
| 8 | Bottom right corner
|===

The next three characters define vertical separators in data rows

[cols="1,5"]
|===
|Index | Description 

| 9  | Left vertical separator
| 10 | Middle vertical separator
| 11 | Right vertical separator

|===

And finally, the last four characters define the different types of horizontal
border, depending on the type of data row or types of adjacent data rows (Row
type will be the subject of the next section)

[cols="1,5"]
|===
|Index | Description 

| 12 | Title, subtitle, footer  
| 13 | Group 
| 14 | Header 
| 15 | Body 

|===

To change a table's border type, simply assign the desired definition to the
`border_type:` parameter when initializing the table.  This can be done in two
ways, either by assigning the 16-character string directly to `border_type:`,
or by assigning the name of one of the 7 predefined borders :

[Literal]
- `BorderName::Ascii`         => `pass:["+++++++++|||----"]`
- `BorderName::ReducedAscii`  => `pass:["E_EE_EE_EE_E----"]`
- `BorderName::Modern`        => `pass:["┌┬┐├┼┤└┴┘│││────"]`
- `BorderName::ReducedModern` => `pass:["E_EE_EE_EE_E────"]`
- `BorderName::Markdown`      => `pass:["___|||___|||__-_"]`
- `BorderName::Fancy`         => `pass:["╭┬╮├┼┤╰┴╯│:│─−-⋅"]`
- `BorderName::Blank`         => `pass:["EEEEEEEEEEEEEEEE"]`

So, for example, to set `border_type:` to `BorderName::ReducedAscii`, I can either :

use the predefined border name
[source,crystal]
----
3	table = Tablo::Table.new([1, 2, 3]
      border_type: Tablo::BorderName::ReducedAscii) do |t|
----

or use its definition string
[source,crystal]
----
3	table = Tablo::Table.new([1, 2, 3]
      border_type: "E_EE_EE_EE_E----") do |t|
----


[literal]
-------------- -------------- --------------
       itself         Double   String       
-------------- -------------- --------------
            1              2   false        
            2              4   true         
            3              6   false        
-------------- -------------- --------------


=== Row types

==== Header and Body
The Header and Body data row types form the basis of table formatting. Other types
can be optionally added to establish the final layout: the Group row type and
Heading row types (Title, SubTitle and Footer).

==== Group
Adjacent columns can share a common header, above the column headers
themselves. This common headers constitute a Group row type.

To create a Group row, simply define a common header after each set of
adjacent columns to be grouped.  

[source,crystal]
----
 1	require "tablo"
 2
 3	table = Tablo::Table.new([1, 2, 3]) do |t|
 4	    t.add_column("itself", &.itself)
 5	    t.add_column(2, header: "Double") {|n| n * 2}
 6	    t.add_group("Numbers")
 7	    t.add_column(:column_3, header: "String") {|n| n.even?.to_s}
 8	    t.add_group("Text")
 9	end
10	puts table
----

[literal]
+-----------------------------+--------------+
|           Numbers           |     Text     |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+

By default, Group headers are centered, but their alignment can be modified
globally at table initialization time with the `group_alignment:` parameter,
or locally for a given group with the `alignment:` parameter.

[source,crystal]
----
 3	table = Tablo::Table.new([1, 2, 3],
      group_alignment: Tablo::Justify::Left) do |t|
----
 
[literal]
| Numbers                     | Text         |

or 

[source,crystal]
----
 8	    t.add_group("Text", alignment: Tablo::Justify::Left)
----
 
[literal]
|           Numbers           | Text         |

Note that the group header can be empty, and that an empty group header is
automatically created if the last column group is not specified.

==== Headings

A formatted table can optionally include a title, subtitle and footer. Each of
these elements is of type FramedHeading or UnFramedHeading.

By default, when the table is initialized, `title:`, `subtitle:` and `footer:` are
of type FramedHeading and their value is `nil`, so they are not displayed.

To display a title (or subtitle or footer), simply specify it when
initializing the table.

[source,crystal]
----
 3	table = Tablo::Table.new([1, 2, 3],
      title: Tablo::FramedHeading.new("Numbers and text")) do |t|
----

[literal]
+--------------------------------------------+
|              Numbers and text              |
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+

or

[source,crystal]
----
 3	table = Tablo::Table.new([1, 2, 3],
      title: Tablo::UnFramedHeading.new("Numbers and text")) do |t|
----
                        
[literal]
               Numbers and text               
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+

In addition to text framing, there's another difference between FramedHeading
and UnFramedHeading. 

FramedHeading accepts 2 additional parameters (`line_breaks_before:` and
`line_breaks_after:`) which allow it to be more or less detached from the
preceding or following text by a number of line breaks.

By default, these parameters are set to 0, and the number of line breaks is
the greater of the current element's `line_breaks_after:` and the next element's
`line_breaks_before:`, if any.

[source,crystal]
----
 3  table = Tablo::Table.new([1, 2, 3],
      title: Tablo::FramedHeading.new("Numbers and text",
        line_breaks_after: 2)) do |t|
----

[literal]
----
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+
----

In summary, we have 6 types of data rows : 

 
[cols="1,2"]
|===
| Type | Description 

| Header  | Always displayed, unless `header_frequency:` is `nil` or
`masked_headers:` is `true`  (_see below_)
| Body    | Always displayed
| Group   | Optional
| Title   | Optional
| Subtitle| Optional
| Footer  | Optional

|===

=== Display frequency and repeated title

An important parameter in table initialization is `header_frequency:` 

- By default, it is set to 0, i.e. rows of data other than body are displayed
only once, at the beginning for titles and headers, at the end for the footer.

[source,crystal]
----
 1  require "tablo"
 2
 3  table = Tablo::Table.new([1, 2, 3],
 4    header_frequency: 0,
 5    title: Tablo::FramedHeading.new("Numbers and text", line_breaks_after: 2),
 6    subtitle: Tablo::UnFramedHeading.new("No booleans"),
 7    footer: Tablo::UnFramedHeading.new("End of page")) do |t|
 8    t.add_column("itself", &.itself)
 9    t.add_column(2, header: "Double") { |n| n * 2 }
10    t.add_group("Numbers")
11    t.add_column(:column_3, header: "String") { |n| n.even?.to_s }
12    t.add_group("Text", alignment: Tablo::Justify::Left)
13  end
14  puts table
----

[literal]
----
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
                  No booleans                 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+
                  End of page         
----

- If set to `nil`, only body rows are displayed.

[source,crystal]
----
 4    header_frequency: nil,
----

[literal]
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
|            3 |            6 | false        |
+--------------+--------------+--------------+

- If set to `n` (positive), group or column headers are repeated every `n` rows, as
are footers, but titles and subtitles are not repeated.

[source,crystal]
----
 4    header_frequency: 2,
----

[literal]
----
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
                  No booleans                 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
+--------------+--------------+--------------+
                  End of page                 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            3 |            6 | false        |
|              |              |              |
+--------------+--------------+--------------+
                  End of page                 
----

However, the `title_repeated:` parameter can be set to `true` to obtain title and
subtitle repetition.

[source,crystal]
----
 4    header_frequency: 2, title_repeated: true,
----

[literal]
----
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
                  No booleans                 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
+--------------+--------------+--------------+
                  End of page                 
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
                  No booleans                 
+-----------------------------+--------------+
|           Numbers           | Text         |
+--------------+--------------+--------------+
|       itself |       Double | String       |
+--------------+--------------+--------------+
|            3 |            6 | false        |
|              |              |              |
+--------------+--------------+--------------+
                  End of page                 
----

=== Extracting, Formatting and Styling
    
At the heart of Tablo's operation lies the Cell, a data structure containing
all the elements required for display. 

==== Extracting

The Cell `value:` attribute contains the raw data.

If extracted from the source for Body rows, the type of the Cell is
a `DataCell`, and the corresponding column header is also a `DataCell` (as it
depends on the type of `value:` for alignment).

If directly given as argument (Headings and Group), the Cell is a `TextCell`
and it does not offer the same flexibility as `DataCell` for formatting and styling.


The type of `value:` is `Tablo::CellType`, which is simply defined as an empty
module restriction type:

[source,crystal]
----
module Tablo::CellType
end
----

This module is already included in all Crystal main scalar types. To
use a (non or less used) scalar type or a user defined class or struct, it is
mandatory to include it by reopening the class or struct. 

For example, to allow a Cell value to contain an array, we could do :

[source,crystal]
----
class Array
  include Tablo::CellType
end

table = Tablo::Table.new([[1, 2], [3, 4]]) do |t|
  t.add_column("itself") { |n| n }
end
puts table
----

[literal]
----
+--------------+
| itself       |
+--------------+
| [1, 2]       |
| [3, 4]       |
+--------------+
----

==== Formatting

Formatting consists in applying a transformation to the raw data to obtain
a character string ready to be displayed. The simplest transformation (and
also the one applied by default) is simply a call to the `to_s` method.

Using a Proc `formatter` allows you to customize the formatting!
Several types of Proc `formatter` exist:

===== TextCell

For `TextCell`, there are 2:
                            
====== 1st form

The first simply expects an argument of type `Tablo:CellType` (the `value:`)

[source,crystal]
----
require "tablo"

table = Tablo::Table.new([1, 2, 3]) do |t|
  t.add_column("itself", &.itself)
  t.add_column(2, header: "Double") { |n| n * 2 }
  t.add_column(3, header: "Float",
    header_formatter: ->(value : Tablo::CellType) { value.as(String).upcase },
    body_formatter: ->(value: Tablo::CellType) {"%.3f" % value.as(Float)}) { |n| n ** 0.5 } 
end
puts table
----


[literal]
----
+--------------+--------------+--------------+
|       itself |       Double |        FLOAT |   <1>
+--------------+--------------+--------------+
|            1 |            2 |        1.000 |
|            2 |            4 |        1.414 |
|            3 |            6 |        1.732 |
+--------------+--------------+--------------+
----

<1> Note that the FLOAT column is aligned to the right, as its alignment is
governed by the type of `value`, which is a float.


If the formatting were done directly at the data extraction level, `value` would
be of type String and column would be aligned to the left. 

[source,crystal]
----
require "tablo"

table = Tablo::Table.new([1, 2, 3]) do |t|
  t.add_column("itself", &.itself)
  t.add_column(2, header: "Double") { |n| n * 2 }
  t.add_column(3, header: "Float",
    header_formatter: ->(value : Tablo::CellType) { value.as(String).upcase } { |n| "%.3f" % (n ** 0.5) }
end
puts table
----

[literal]
----
+--------------+--------------+--------------+
|       itself |       Double | FLOAT        |
+--------------+--------------+--------------+
|            1 |            2 | 1.000        |
|            2 |            4 | 1.414        |
|            3 |            6 | 1.732        |
+--------------+--------------+--------------+
----

====== 2nd form

The second expects an additional argument (of type `Int32`) corresponding to
the column width (for special use cases, like text stretching)
  
[source,crystal]
----
require "tablo"

table = Tablo::Table.new([1, 2, 3]) do |t|
  t.add_column("itself", &.itself)
  t.add_column(2, header: "Double") { |n| n * 2 }
  t.add_column(3, header: "Float",
    header_formatter: ->(value : Tablo::CellType, width : Int32)
    { Tablo::Util.stretch(value.as(String), width, ' ')}, 
    body_formatter: ->(value : Tablo::CellType)
    { Tablo::Util.dot_align(value, 4, Tablo::Util::DotAlign::Blank) }) {|n| n ** 0.5 }
  t.add_column(:column_4, header: "String") { |n| n.even?.to_s }
end
puts table
----

[literal]
----
+--------------+--------------+--------------+--------------+
|       itself |       Double |    F l o a t | String       |
+--------------+--------------+--------------+--------------+
|            1 |            2 |       1      | false        |
|            2 |            4 |       1.4142 | true         |
|            3 |            6 |       1.7321 | false        |
+--------------+--------------+--------------+--------------+
----

In the example, we also use the first form to illustrate another utility
method : `Tablo::Util.dot_align`. +
_See full API for `Tablo::Util` methods_

===== DataCell

For `DataCell`, there are 4 possible formatter types, 2 of which are identical
to those of TextCell, so we will look here at only the 3rd and 4th form.

====== 3rd form

in Proc(CellType, CellData, String)
formatter.call(@value, @cell_data)

====== 4th form
in Proc(CellType, CellData, Int32, String)
formatter.call(@value, @cell_data, @width)

[Literal]
----
TEXTCELL

formatter
    2 forms :
    value, width
    value
styler
    2 forms :                 
    content, line_index
    content

DATACELL

formatter
    2 forms :
    value, cell_data
    value
    or perhaps 3:
    value, cell_data
    value, width
    value
    or perhaps 4: YES
    value, cell_data, width
    value, cell_data
    value, width
    value

styler
    forms :
    value, cell_data, content, line_index
    value, cell_data, content
    value, content

TEXTCELL
    def apply_formatter
      # @formatter.call(@value)
      case formatter = @formatter
      in Proc(CellType, Int32, String)
        formatter.call(@value, @width)
      in Proc(CellType, String)
        formatter.call(@value)
      end
    end

2 forms :
value, width
value

    # :nodoc:
    def apply_styler(content, line_index)
      # debug!(Util.styler_allowed)
      return content unless Util.styler_allowed
      case styler = @styler
      in Proc(String, Int32, String)
        styler.call(content, line_index)
      in Proc(String, String)
        styler.call(content)
      end
    end
2 forms :                 
content, line_index
content

DATACELL
    def apply_formatter
      # debug!("in DataCell apply_formatter")
      case formatter = @formatter
      in Proc(CellType, CellData, String)
        formatter.call(@value, @cell_data)
        # Useless as width is included into celldata
        # in Proc(CellType, Int32, String)
        #  formatter.call(@value, @width)
      in Proc(CellType, String)
        formatter.call(@value)
      end
    end
  2 forms :
  value, cell_data
  value
  or perhaps 3:
  value, cell_data
  value, width
  value

    # :nodoc:
    def apply_styler(content, line_index)
      # debug!(Util.styler_allowed)
      return content unless Util.styler_allowed
      case styler = @styler
      in Proc(CellType, String, CellData, Int32, String)
        styler.call(@value, content, @cell_data, line_index)
      in Proc(CellType, String, CellData, String)
        styler.call(@value, content, @cell_data)
      in Proc(CellType, String, String)
        styler.call(@value, content)
      end
    end
forms :
value, content, cell_data, line_index
value, content, cell_data
value, content
    
----





TODO TODO TODO
Modifier le 2nd pour correspondre au second de DataCall
Ajouter un 3ème : CellType, Int32 (line), Int32 (width) ???

A voir !!!

TODO TODO TODO

For DataCell, there are 3:

- The first simply expects an argument of type Tablo:CellType (the `value:`)

- The second expects an additional argument (of type Int32) corresponding to
  the line number when the cell contains potentially more than one. This
  enables conditional formatting.

- the third expects a CellType as first argument, and a CellData type as
  second. 
  And CellData also contain width

[source,crystal]
----
struct CellData
  getter value, row_index, column_index, width

  def initialize(@value : CellType, @row_index : Int32, @column_index : Int32, @width : Int32)
  end
end
----

A CellData attribute is stored in each DataCell, allowing any kind
of conditional formatting, based on row or column index.



as fProc(CellType, Int32, String) |
- Proc(CellType, String)
  alias DataCellFormatter = Proc(CellType, CellData, String) |
                            Proc(CellType, Int32, String) |
                            Proc(CellType, String)
- The second expects an additional argument (of type Int32) corresponding to
  the line number when the cell contains potentially more than one. This
  enables conditional formatting.

==== Styling


TODO  padding, truncation

TODO row_divider_frequency

TODO wrap

TODO masked_headers (double emploi avec header_frequency: nil ?)

TODO omit_last_rule

TODO footer_page_break


== Complete API

=== Tablo internals
Table definition is largely based on default values, which can be modified via
named parameters if required.

Most of the parameters defined when initializing a table are taken over by
default, if appropriate, when creating columns.

Tablo features a column-based rather than row-based API, which means
that header and body lines are automatically synchronized. 

At the heart of Tablo's operation lies the cell, a data structure containing
all the elements required for display. There are 2 different types of cell:

- Those containing source or source-dependent data, the DataCell type (for Header and Body rows)
- Text cells, the TextCell type (for Group and Headings)

They differ mainly in 2 exclusive attribute types:

- RowType for TextCell cells

- CellData for DataCell cells

Both have the `value:` attribute, which contains the raw data extracted from
source. Its type is `Tablo::CellType`


[literal]
----
+--------------------------------------------+
|              Numbers and text              |
+--------------------------------------------+
 
                  No booleans                 
+--------------+--------------+--------------+
|            1 |            2 | false        |
|            2 |            4 | true         |
+--------------+--------------+--------------+
                  End of page                 
+--------------+--------------+--------------+
|            3 |            6 | false        |
|              |              |              |
+--------------+--------------+--------------+
                  End of page                 
----


////
== Overview


To give you a taste of both the richness of the layout, here's an example that's somewhat contrived, but interesting to study.

image::docs/assets/images/overview.svg[width="400",caption="Figure 8:"]

{empty} +

and the corresponding source code.

[source,crystal]
----
include::docs/assets/sources/overview.cr[]
----

////
